name: mindvista-env

services:
    postgres:
        image: postgres:15
        env_file: .env # copied from .env.development
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-mindvista}
            POSTGRES_USER: ${POSTGRES_USER:-mindvista}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mindvista}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    localstack:
        image: localstack/localstack:latest
        env_file: .env # copied from .env.development
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=${S3_REGION:-ca-central-1}
            - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-test}
            - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-test}
            - DOCKER_HOST=unix:///var/run/docker.sock
        ports:
            - "4566:4566"
        volumes:
            - localstack_data:/var/lib/localstack
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    postgres_data:
    localstack_data:
