/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import { pgTable, index, uniqueIndex, foreignKey, serial, varchar, timestamp, numeric, integer, jsonb, boolean, pgEnum } from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "contentEditor", "contentEditorFr"]);
export const enum_legal_status = pgEnum("enum_legal_status", ["draft", "published"]);
export const enum__legal_v_version_status = pgEnum("enum__legal_v_version_status", ["draft", "published"]);
export const enum_audit_log_operation = pgEnum("enum_audit_log_operation", ["create", "read", "update", "delete"]);
export const enum_sponsor_status = pgEnum("enum_sponsor_status", ["draft", "published"]);
export const enum__sponsor_v_version_status = pgEnum("enum__sponsor_v_version_status", ["draft", "published"]);
export const enum_volunteer_status = pgEnum("enum_volunteer_status", ["draft", "published"]);
export const enum__volunteer_v_version_status = pgEnum("enum__volunteer_v_version_status", ["draft", "published"]);
export const enum_announcement_bar_status = pgEnum("enum_announcement_bar_status", ["draft", "published"]);
export const enum__announcement_bar_v_version_status = pgEnum("enum__announcement_bar_v_version_status", ["draft", "published"]);
export const enum_about_status = pgEnum("enum_about_status", ["draft", "published"]);
export const enum__about_v_version_status = pgEnum("enum__about_v_version_status", ["draft", "published"]);

export const users = pgTable(
    "users",
    {
        id: serial("id").primaryKey(),
        fullName: varchar("full_name").notNull(),
        role: enum_users_role("role").notNull().default("contentEditor"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        email: varchar("email").notNull(),
        resetPasswordToken: varchar("reset_password_token"),
        resetPasswordExpiration: timestamp("reset_password_expiration", { mode: "string", withTimezone: true, precision: 3 }),
        salt: varchar("salt"),
        hash: varchar("hash"),
        loginAttempts: numeric("login_attempts").default("0"),
        lockUntil: timestamp("lock_until", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
        users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
        users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
    }),
);

export const media = pgTable(
    "media",
    {
        id: serial("id").primaryKey(),
        alt: varchar("alt").notNull(),
        altFr: varchar("alt_fr"),
        purpose: varchar("purpose").notNull(),
        prefix: varchar("prefix").default("media"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        url: varchar("url"),
        thumbnailURL: varchar("thumbnail_u_r_l"),
        filename: varchar("filename"),
        mimeType: varchar("mime_type"),
        filesize: numeric("filesize"),
        width: numeric("width"),
        height: numeric("height"),
        focalX: numeric("focal_x"),
        focalY: numeric("focal_y"),
    },
    (columns) => ({
        media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
        media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
        media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
    }),
);

export const pages = pgTable(
    "pages",
    {
        id: serial("id").primaryKey(),
        slug: varchar("slug").notNull(),
        title: varchar("title").notNull(),
        titleFr: varchar("title_fr"),
        seoDescription: varchar("seo_description").notNull(),
        seoDescriptionFr: varchar("seo_description_fr"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        pages_slug_idx: uniqueIndex("pages_slug_idx").on(columns.slug),
        pages_updated_at_idx: index("pages_updated_at_idx").on(columns.updatedAt),
        pages_created_at_idx: index("pages_created_at_idx").on(columns.createdAt),
    }),
);

export const legal = pgTable(
    "legal",
    {
        id: serial("id").primaryKey(),
        page: integer("page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        content: jsonb("content"),
        contentFr: jsonb("content_fr"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        _status: enum_legal_status("_status").default("draft"),
    },
    (columns) => ({
        legal_page_idx: index("legal_page_idx").on(columns.page),
        legal_updated_at_idx: index("legal_updated_at_idx").on(columns.updatedAt),
        legal_created_at_idx: index("legal_created_at_idx").on(columns.createdAt),
        legal__status_idx: index("legal__status_idx").on(columns._status),
    }),
);

export const _legal_v = pgTable(
    "_legal_v",
    {
        id: serial("id").primaryKey(),
        parent: integer("parent_id").references(() => legal.id, {
            onDelete: "set null",
        }),
        version_page: integer("version_page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        version_content: jsonb("version_content"),
        version_contentFr: jsonb("version_content_fr"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        version__status: enum__legal_v_version_status("version__status").default("draft"),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        latest: boolean("latest"),
    },
    (columns) => ({
        _legal_v_parent_idx: index("_legal_v_parent_idx").on(columns.parent),
        _legal_v_version_version_page_idx: index("_legal_v_version_version_page_idx").on(columns.version_page),
        _legal_v_version_version_updated_at_idx: index("_legal_v_version_version_updated_at_idx").on(columns.version_updatedAt),
        _legal_v_version_version_created_at_idx: index("_legal_v_version_version_created_at_idx").on(columns.version_createdAt),
        _legal_v_version_version__status_idx: index("_legal_v_version_version__status_idx").on(columns.version__status),
        _legal_v_created_at_idx: index("_legal_v_created_at_idx").on(columns.createdAt),
        _legal_v_updated_at_idx: index("_legal_v_updated_at_idx").on(columns.updatedAt),
        _legal_v_latest_idx: index("_legal_v_latest_idx").on(columns.latest),
    }),
);

export const events_date_ranges = pgTable(
    "events_date_ranges",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        startDate: timestamp("start_date", { mode: "string", withTimezone: true, precision: 3 }).notNull(),
        endDate: timestamp("end_date", { mode: "string", withTimezone: true, precision: 3 }).notNull(),
    },
    (columns) => ({
        _orderIdx: index("events_date_ranges_order_idx").on(columns._order),
        _parentIDIdx: index("events_date_ranges_parent_id_idx").on(columns._parentID),
        events_date_ranges_start_date_idx: index("events_date_ranges_start_date_idx").on(columns.startDate),
        events_date_ranges_end_date_idx: index("events_date_ranges_end_date_idx").on(columns.endDate),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [events.id],
            name: "events_date_ranges_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const events = pgTable(
    "events",
    {
        id: serial("id").primaryKey(),
        slug: varchar("slug").notNull(),
        title: varchar("title").notNull(),
        titleFr: varchar("title_fr"),
        description: varchar("description").notNull(),
        descriptionFr: varchar("description_fr"),
        incentive: varchar("incentive"),
        incentiveFr: varchar("incentive_fr"),
        limitedAvailability: boolean("limited_availability"),
        isChance: boolean("is_chance"),
        location: varchar("location").notNull(),
        locationFr: varchar("location_fr"),
        locationLink: varchar("location_link"),
        signUpLink: varchar("sign_up_link"),
        instagramPost: varchar("instagram_post"),
        graphic: integer("graphic_id").references(() => media.id, {
            onDelete: "set null",
        }),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        events_slug_idx: uniqueIndex("events_slug_idx").on(columns.slug),
        events_graphic_idx: index("events_graphic_idx").on(columns.graphic),
        events_updated_at_idx: index("events_updated_at_idx").on(columns.updatedAt),
        events_created_at_idx: index("events_created_at_idx").on(columns.createdAt),
    }),
);

export const clubs_other_socials = pgTable(
    "clubs_other_socials",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        link: varchar("link").notNull(),
    },
    (columns) => ({
        _orderIdx: index("clubs_other_socials_order_idx").on(columns._order),
        _parentIDIdx: index("clubs_other_socials_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [clubs.id],
            name: "clubs_other_socials_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const clubs = pgTable(
    "clubs",
    {
        id: serial("id").primaryKey(),
        slug: varchar("slug").notNull(),
        title: varchar("title").notNull(),
        titleFr: varchar("title_fr"),
        description: varchar("description").notNull(),
        descriptionFr: varchar("description_fr"),
        website: varchar("website"),
        newsletter: varchar("newsletter"),
        email: varchar("email"),
        phoneNumber: varchar("phone_number"),
        facebook: varchar("facebook"),
        instagram: varchar("instagram"),
        graphicTitle: varchar("graphic_title"),
        graphicTitleFr: varchar("graphic_title_fr"),
        graphic: integer("graphic_id").references(() => media.id, {
            onDelete: "set null",
        }),
        currentlyActive: boolean("currently_active"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        clubs_slug_idx: uniqueIndex("clubs_slug_idx").on(columns.slug),
        clubs_graphic_idx: index("clubs_graphic_idx").on(columns.graphic),
        clubs_updated_at_idx: index("clubs_updated_at_idx").on(columns.updatedAt),
        clubs_created_at_idx: index("clubs_created_at_idx").on(columns.createdAt),
    }),
);

export const clubs_rels = pgTable(
    "clubs_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: varchar("path").notNull(),
        "club-tagsID": integer("club_tags_id"),
    },
    (columns) => ({
        order: index("clubs_rels_order_idx").on(columns.order),
        parentIdx: index("clubs_rels_parent_idx").on(columns.parent),
        pathIdx: index("clubs_rels_path_idx").on(columns.path),
        clubs_rels_club_tags_id_idx: index("clubs_rels_club_tags_id_idx").on(columns["club-tagsID"]),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [clubs.id],
            name: "clubs_rels_parent_fk",
        }).onDelete("cascade"),
        "club-tagsIdFk": foreignKey({
            columns: [columns["club-tagsID"]],
            foreignColumns: [club_tags.id],
            name: "clubs_rels_club_tags_fk",
        }).onDelete("cascade"),
    }),
);

export const resources_insurance_providers_insurance_provider = pgTable(
    "resources_insurance_providers_insurance_provider",
    {
        _order: integer("_order").notNull(),
        _parentID: varchar("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        name: varchar("name").notNull(),
        nameFr: varchar("name_fr"),
        description: varchar("description"),
        descriptionFr: varchar("description_fr"),
    },
    (columns) => ({
        _orderIdx: index("resources_insurance_providers_insurance_provider_order_idx").on(columns._order),
        _parentIDIdx: index("resources_insurance_providers_insurance_provider_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [resources_insurance_providers.id],
            name: "resources_insurance_providers_insurance_provider_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const resources_insurance_providers = pgTable(
    "resources_insurance_providers",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
    },
    (columns) => ({
        _orderIdx: index("resources_insurance_providers_order_idx").on(columns._order),
        _parentIDIdx: index("resources_insurance_providers_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [resources.id],
            name: "resources_insurance_providers_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const resources = pgTable(
    "resources",
    {
        id: serial("id").primaryKey(),
        slug: varchar("slug").notNull(),
        title: varchar("title").notNull(),
        titleFr: varchar("title_fr"),
        description: varchar("description").notNull(),
        descriptionFr: varchar("description_fr"),
        website: varchar("website"),
        newsletter: varchar("newsletter"),
        insuranceDetails: varchar("insurance_details"),
        insuranceDetailFr: varchar("insurance_detail_fr"),
        email: varchar("email"),
        phoneNumber: varchar("phone_number"),
        location: varchar("location"),
        locationFr: varchar("location_fr"),
        channelOnline: boolean("channel_online"),
        channelTelephone: boolean("channel_telephone"),
        channelInPerson: boolean("channel_in_person"),
        onCampus: boolean("on_campus"),
        graphicTitle: varchar("graphic_title"),
        graphicTitleFr: varchar("graphic_title_fr"),
        graphic: integer("graphic_id").references(() => media.id, {
            onDelete: "set null",
        }),
        currentlyActive: boolean("currently_active"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        resources_slug_idx: uniqueIndex("resources_slug_idx").on(columns.slug),
        resources_graphic_idx: index("resources_graphic_idx").on(columns.graphic),
        resources_updated_at_idx: index("resources_updated_at_idx").on(columns.updatedAt),
        resources_created_at_idx: index("resources_created_at_idx").on(columns.createdAt),
    }),
);

export const resources_rels = pgTable(
    "resources_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: varchar("path").notNull(),
        "resource-tagsID": integer("resource_tags_id"),
    },
    (columns) => ({
        order: index("resources_rels_order_idx").on(columns.order),
        parentIdx: index("resources_rels_parent_idx").on(columns.parent),
        pathIdx: index("resources_rels_path_idx").on(columns.path),
        resources_rels_resource_tags_id_idx: index("resources_rels_resource_tags_id_idx").on(columns["resource-tagsID"]),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [resources.id],
            name: "resources_rels_parent_fk",
        }).onDelete("cascade"),
        "resource-tagsIdFk": foreignKey({
            columns: [columns["resource-tagsID"]],
            foreignColumns: [resource_tags.id],
            name: "resources_rels_resource_tags_fk",
        }).onDelete("cascade"),
    }),
);

export const club_tag_categories = pgTable(
    "club_tag_categories",
    {
        id: serial("id").primaryKey(),
        name: varchar("name").notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        club_tag_categories_updated_at_idx: index("club_tag_categories_updated_at_idx").on(columns.updatedAt),
        club_tag_categories_created_at_idx: index("club_tag_categories_created_at_idx").on(columns.createdAt),
    }),
);

export const resource_tag_categories = pgTable(
    "resource_tag_categories",
    {
        id: serial("id").primaryKey(),
        name: varchar("name").notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        resource_tag_categories_updated_at_idx: index("resource_tag_categories_updated_at_idx").on(columns.updatedAt),
        resource_tag_categories_created_at_idx: index("resource_tag_categories_created_at_idx").on(columns.createdAt),
    }),
);

export const club_tags = pgTable(
    "club_tags",
    {
        id: serial("id").primaryKey(),
        name: varchar("name").notNull(),
        category: integer("category_id")
            .notNull()
            .references(() => club_tag_categories.id, {
                onDelete: "set null",
            }),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        club_tags_category_idx: index("club_tags_category_idx").on(columns.category),
        club_tags_updated_at_idx: index("club_tags_updated_at_idx").on(columns.updatedAt),
        club_tags_created_at_idx: index("club_tags_created_at_idx").on(columns.createdAt),
    }),
);

export const resource_tags = pgTable(
    "resource_tags",
    {
        id: serial("id").primaryKey(),
        name: varchar("name").notNull(),
        category: integer("category_id")
            .notNull()
            .references(() => resource_tag_categories.id, {
                onDelete: "set null",
            }),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        resource_tags_category_idx: index("resource_tags_category_idx").on(columns.category),
        resource_tags_updated_at_idx: index("resource_tags_updated_at_idx").on(columns.updatedAt),
        resource_tags_created_at_idx: index("resource_tags_created_at_idx").on(columns.createdAt),
    }),
);

export const audit_log = pgTable(
    "audit_log",
    {
        id: serial("id").primaryKey(),
        timestamp: timestamp("timestamp", { mode: "string", withTimezone: true, precision: 3 }).notNull(),
        operation: enum_audit_log_operation("operation").notNull(),
        resourceURL: varchar("resource_u_r_l").notNull(),
        documentId: varchar("document_id").notNull(),
        previousVersionId: varchar("previous_version_id"),
        user: integer("user_id").references(() => users.id, {
            onDelete: "set null",
        }),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        audit_log_user_idx: index("audit_log_user_idx").on(columns.user),
        audit_log_updated_at_idx: index("audit_log_updated_at_idx").on(columns.updatedAt),
        audit_log_created_at_idx: index("audit_log_created_at_idx").on(columns.createdAt),
    }),
);

export const payload_locked_documents = pgTable(
    "payload_locked_documents",
    {
        id: serial("id").primaryKey(),
        globalSlug: varchar("global_slug"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        payload_locked_documents_global_slug_idx: index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
        payload_locked_documents_updated_at_idx: index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
        payload_locked_documents_created_at_idx: index("payload_locked_documents_created_at_idx").on(columns.createdAt),
    }),
);

export const payload_locked_documents_rels = pgTable(
    "payload_locked_documents_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: varchar("path").notNull(),
        usersID: integer("users_id"),
        mediaID: integer("media_id"),
        pagesID: integer("pages_id"),
        legalID: integer("legal_id"),
        eventsID: integer("events_id"),
        clubsID: integer("clubs_id"),
        resourcesID: integer("resources_id"),
        "club-tag-categoriesID": integer("club_tag_categories_id"),
        "resource-tag-categoriesID": integer("resource_tag_categories_id"),
        "club-tagsID": integer("club_tags_id"),
        "resource-tagsID": integer("resource_tags_id"),
        "audit-logID": integer("audit_log_id"),
    },
    (columns) => ({
        order: index("payload_locked_documents_rels_order_idx").on(columns.order),
        parentIdx: index("payload_locked_documents_rels_parent_idx").on(columns.parent),
        pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
        payload_locked_documents_rels_users_id_idx: index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
        payload_locked_documents_rels_media_id_idx: index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
        payload_locked_documents_rels_pages_id_idx: index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
        payload_locked_documents_rels_legal_id_idx: index("payload_locked_documents_rels_legal_id_idx").on(columns.legalID),
        payload_locked_documents_rels_events_id_idx: index("payload_locked_documents_rels_events_id_idx").on(columns.eventsID),
        payload_locked_documents_rels_clubs_id_idx: index("payload_locked_documents_rels_clubs_id_idx").on(columns.clubsID),
        payload_locked_documents_rels_resources_id_idx: index("payload_locked_documents_rels_resources_id_idx").on(columns.resourcesID),
        payload_locked_documents_rels_club_tag_categories_id_idx: index("payload_locked_documents_rels_club_tag_categories_id_idx").on(columns["club-tag-categoriesID"]),
        payload_locked_documents_rels_resource_tag_categories_id_idx: index("payload_locked_documents_rels_resource_tag_categories_id_idx").on(columns["resource-tag-categoriesID"]),
        payload_locked_documents_rels_club_tags_id_idx: index("payload_locked_documents_rels_club_tags_id_idx").on(columns["club-tagsID"]),
        payload_locked_documents_rels_resource_tags_id_idx: index("payload_locked_documents_rels_resource_tags_id_idx").on(columns["resource-tagsID"]),
        payload_locked_documents_rels_audit_log_id_idx: index("payload_locked_documents_rels_audit_log_id_idx").on(columns["audit-logID"]),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_locked_documents.id],
            name: "payload_locked_documents_rels_parent_fk",
        }).onDelete("cascade"),
        usersIdFk: foreignKey({
            columns: [columns["usersID"]],
            foreignColumns: [users.id],
            name: "payload_locked_documents_rels_users_fk",
        }).onDelete("cascade"),
        mediaIdFk: foreignKey({
            columns: [columns["mediaID"]],
            foreignColumns: [media.id],
            name: "payload_locked_documents_rels_media_fk",
        }).onDelete("cascade"),
        pagesIdFk: foreignKey({
            columns: [columns["pagesID"]],
            foreignColumns: [pages.id],
            name: "payload_locked_documents_rels_pages_fk",
        }).onDelete("cascade"),
        legalIdFk: foreignKey({
            columns: [columns["legalID"]],
            foreignColumns: [legal.id],
            name: "payload_locked_documents_rels_legal_fk",
        }).onDelete("cascade"),
        eventsIdFk: foreignKey({
            columns: [columns["eventsID"]],
            foreignColumns: [events.id],
            name: "payload_locked_documents_rels_events_fk",
        }).onDelete("cascade"),
        clubsIdFk: foreignKey({
            columns: [columns["clubsID"]],
            foreignColumns: [clubs.id],
            name: "payload_locked_documents_rels_clubs_fk",
        }).onDelete("cascade"),
        resourcesIdFk: foreignKey({
            columns: [columns["resourcesID"]],
            foreignColumns: [resources.id],
            name: "payload_locked_documents_rels_resources_fk",
        }).onDelete("cascade"),
        "club-tag-categoriesIdFk": foreignKey({
            columns: [columns["club-tag-categoriesID"]],
            foreignColumns: [club_tag_categories.id],
            name: "payload_locked_documents_rels_club_tag_categories_fk",
        }).onDelete("cascade"),
        "resource-tag-categoriesIdFk": foreignKey({
            columns: [columns["resource-tag-categoriesID"]],
            foreignColumns: [resource_tag_categories.id],
            name: "payload_locked_documents_rels_resource_tag_categories_fk",
        }).onDelete("cascade"),
        "club-tagsIdFk": foreignKey({
            columns: [columns["club-tagsID"]],
            foreignColumns: [club_tags.id],
            name: "payload_locked_documents_rels_club_tags_fk",
        }).onDelete("cascade"),
        "resource-tagsIdFk": foreignKey({
            columns: [columns["resource-tagsID"]],
            foreignColumns: [resource_tags.id],
            name: "payload_locked_documents_rels_resource_tags_fk",
        }).onDelete("cascade"),
        "audit-logIdFk": foreignKey({
            columns: [columns["audit-logID"]],
            foreignColumns: [audit_log.id],
            name: "payload_locked_documents_rels_audit_log_fk",
        }).onDelete("cascade"),
    }),
);

export const payload_preferences = pgTable(
    "payload_preferences",
    {
        id: serial("id").primaryKey(),
        key: varchar("key"),
        value: jsonb("value"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        payload_preferences_key_idx: index("payload_preferences_key_idx").on(columns.key),
        payload_preferences_updated_at_idx: index("payload_preferences_updated_at_idx").on(columns.updatedAt),
        payload_preferences_created_at_idx: index("payload_preferences_created_at_idx").on(columns.createdAt),
    }),
);

export const payload_preferences_rels = pgTable(
    "payload_preferences_rels",
    {
        id: serial("id").primaryKey(),
        order: integer("order"),
        parent: integer("parent_id").notNull(),
        path: varchar("path").notNull(),
        usersID: integer("users_id"),
    },
    (columns) => ({
        order: index("payload_preferences_rels_order_idx").on(columns.order),
        parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
        pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
        payload_preferences_rels_users_id_idx: index("payload_preferences_rels_users_id_idx").on(columns.usersID),
        parentFk: foreignKey({
            columns: [columns["parent"]],
            foreignColumns: [payload_preferences.id],
            name: "payload_preferences_rels_parent_fk",
        }).onDelete("cascade"),
        usersIdFk: foreignKey({
            columns: [columns["usersID"]],
            foreignColumns: [users.id],
            name: "payload_preferences_rels_users_fk",
        }).onDelete("cascade"),
    }),
);

export const payload_migrations = pgTable(
    "payload_migrations",
    {
        id: serial("id").primaryKey(),
        name: varchar("name"),
        batch: numeric("batch"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        payload_migrations_updated_at_idx: index("payload_migrations_updated_at_idx").on(columns.updatedAt),
        payload_migrations_created_at_idx: index("payload_migrations_created_at_idx").on(columns.createdAt),
    }),
);

export const holistic_wellness_wellness_wheel_dimensions = pgTable(
    "holistic_wellness_wellness_wheel_dimensions",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        name: varchar("name").notNull(),
        nameFr: varchar("name_fr"),
        description: varchar("description").notNull(),
        descriptionFr: varchar("description_fr"),
        color: varchar("color").notNull(),
    },
    (columns) => ({
        _orderIdx: index("holistic_wellness_wellness_wheel_dimensions_order_idx").on(columns._order),
        _parentIDIdx: index("holistic_wellness_wellness_wheel_dimensions_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [holistic_wellness.id],
            name: "holistic_wellness_wellness_wheel_dimensions_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const holistic_wellness_sections = pgTable(
    "holistic_wellness_sections",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        content: jsonb("content").notNull(),
        contentFr: jsonb("content_fr"),
    },
    (columns) => ({
        _orderIdx: index("holistic_wellness_sections_order_idx").on(columns._order),
        _parentIDIdx: index("holistic_wellness_sections_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [holistic_wellness.id],
            name: "holistic_wellness_sections_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const holistic_wellness = pgTable(
    "holistic_wellness",
    {
        id: serial("id").primaryKey(),
        page: integer("page_id")
            .notNull()
            .references(() => pages.id, {
                onDelete: "set null",
            }),
        heroContent: jsonb("hero_content").notNull(),
        heroContentFr: jsonb("hero_content_fr"),
        wellnessWheelTopContent: jsonb("wellness_wheel_top_content").notNull(),
        wellnessWheelTopContentFr: jsonb("wellness_wheel_top_content_fr"),
        wellnessWheelBottomContent: jsonb("wellness_wheel_bottom_content").notNull(),
        wellnessWheelBottomContentFr: jsonb("wellness_wheel_bottom_content_fr"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        holistic_wellness_page_idx: index("holistic_wellness_page_idx").on(columns.page),
    }),
);

export const _holistic_wellness_v_version_wellness_wheel_dimensions = pgTable(
    "_holistic_wellness_v_version_wellness_wheel_dimensions",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        name: varchar("name").notNull(),
        nameFr: varchar("name_fr"),
        description: varchar("description").notNull(),
        descriptionFr: varchar("description_fr"),
        color: varchar("color").notNull(),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_holistic_wellness_v_version_wellness_wheel_dimensions_order_idx").on(columns._order),
        _parentIDIdx: index("_holistic_wellness_v_version_wellness_wheel_dimensions_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_holistic_wellness_v.id],
            name: "_holistic_wellness_v_version_wellness_wheel_dimensions_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _holistic_wellness_v_version_sections = pgTable(
    "_holistic_wellness_v_version_sections",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        content: jsonb("content").notNull(),
        contentFr: jsonb("content_fr"),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_holistic_wellness_v_version_sections_order_idx").on(columns._order),
        _parentIDIdx: index("_holistic_wellness_v_version_sections_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_holistic_wellness_v.id],
            name: "_holistic_wellness_v_version_sections_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _holistic_wellness_v = pgTable(
    "_holistic_wellness_v",
    {
        id: serial("id").primaryKey(),
        version_page: integer("version_page_id")
            .notNull()
            .references(() => pages.id, {
                onDelete: "set null",
            }),
        version_heroContent: jsonb("version_hero_content").notNull(),
        version_heroContentFr: jsonb("version_hero_content_fr"),
        version_wellnessWheelTopContent: jsonb("version_wellness_wheel_top_content").notNull(),
        version_wellnessWheelTopContentFr: jsonb("version_wellness_wheel_top_content_fr"),
        version_wellnessWheelBottomContent: jsonb("version_wellness_wheel_bottom_content").notNull(),
        version_wellnessWheelBottomContentFr: jsonb("version_wellness_wheel_bottom_content_fr"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
    },
    (columns) => ({
        _holistic_wellness_v_version_version_page_idx: index("_holistic_wellness_v_version_version_page_idx").on(columns.version_page),
        _holistic_wellness_v_created_at_idx: index("_holistic_wellness_v_created_at_idx").on(columns.createdAt),
        _holistic_wellness_v_updated_at_idx: index("_holistic_wellness_v_updated_at_idx").on(columns.updatedAt),
    }),
);

export const sponsor_sponsors = pgTable(
    "sponsor_sponsors",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        url: varchar("url"),
        logo: integer("logo_id").references(() => media.id, {
            onDelete: "set null",
        }),
    },
    (columns) => ({
        _orderIdx: index("sponsor_sponsors_order_idx").on(columns._order),
        _parentIDIdx: index("sponsor_sponsors_parent_id_idx").on(columns._parentID),
        sponsor_sponsors_logo_idx: index("sponsor_sponsors_logo_idx").on(columns.logo),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [sponsor.id],
            name: "sponsor_sponsors_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const sponsor = pgTable(
    "sponsor",
    {
        id: serial("id").primaryKey(),
        page: integer("page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        ourSponsorsSection: varchar("our_sponsors_section"),
        ourSponsorsSectionFr: varchar("our_sponsors_section_fr"),
        callout: varchar("callout"),
        calloutFr: varchar("callout_fr"),
        sponsorUsSection: varchar("sponsor_us_section"),
        sponsorUsSectionFr: varchar("sponsor_us_section_fr"),
        _status: enum_sponsor_status("_status").default("draft"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        sponsor_page_idx: index("sponsor_page_idx").on(columns.page),
        sponsor__status_idx: index("sponsor__status_idx").on(columns._status),
    }),
);

export const _sponsor_v_version_sponsors = pgTable(
    "_sponsor_v_version_sponsors",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        url: varchar("url"),
        logo: integer("logo_id").references(() => media.id, {
            onDelete: "set null",
        }),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_sponsor_v_version_sponsors_order_idx").on(columns._order),
        _parentIDIdx: index("_sponsor_v_version_sponsors_parent_id_idx").on(columns._parentID),
        _sponsor_v_version_sponsors_logo_idx: index("_sponsor_v_version_sponsors_logo_idx").on(columns.logo),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_sponsor_v.id],
            name: "_sponsor_v_version_sponsors_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _sponsor_v = pgTable(
    "_sponsor_v",
    {
        id: serial("id").primaryKey(),
        version_page: integer("version_page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        version_ourSponsorsSection: varchar("version_our_sponsors_section"),
        version_ourSponsorsSectionFr: varchar("version_our_sponsors_section_fr"),
        version_callout: varchar("version_callout"),
        version_calloutFr: varchar("version_callout_fr"),
        version_sponsorUsSection: varchar("version_sponsor_us_section"),
        version_sponsorUsSectionFr: varchar("version_sponsor_us_section_fr"),
        version__status: enum__sponsor_v_version_status("version__status").default("draft"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        latest: boolean("latest"),
    },
    (columns) => ({
        _sponsor_v_version_version_page_idx: index("_sponsor_v_version_version_page_idx").on(columns.version_page),
        _sponsor_v_version_version__status_idx: index("_sponsor_v_version_version__status_idx").on(columns.version__status),
        _sponsor_v_created_at_idx: index("_sponsor_v_created_at_idx").on(columns.createdAt),
        _sponsor_v_updated_at_idx: index("_sponsor_v_updated_at_idx").on(columns.updatedAt),
        _sponsor_v_latest_idx: index("_sponsor_v_latest_idx").on(columns.latest),
    }),
);

export const volunteer_positions = pgTable(
    "volunteer_positions",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        title: varchar("title"),
        titleFr: varchar("title_fr"),
        description: jsonb("description"),
        descriptionFr: jsonb("description_fr"),
        requirements: jsonb("requirements"),
        requirementsFr: jsonb("requirements_fr"),
        timeCommitment: varchar("time_commitment"),
        timeCommitmentFr: varchar("time_commitment_fr"),
        datePosted: timestamp("date_posted", { mode: "string", withTimezone: true, precision: 3 }),
        formLink: varchar("form_link"),
        isOpen: boolean("is_open").default(true),
    },
    (columns) => ({
        _orderIdx: index("volunteer_positions_order_idx").on(columns._order),
        _parentIDIdx: index("volunteer_positions_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [volunteer.id],
            name: "volunteer_positions_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const volunteer = pgTable(
    "volunteer",
    {
        id: serial("id").primaryKey(),
        page: integer("page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        title: varchar("title"),
        titleFr: varchar("title_fr"),
        description: varchar("description"),
        descriptionFr: varchar("description_fr"),
        _status: enum_volunteer_status("_status").default("draft"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        volunteer_page_idx: index("volunteer_page_idx").on(columns.page),
        volunteer__status_idx: index("volunteer__status_idx").on(columns._status),
    }),
);

export const _volunteer_v_version_positions = pgTable(
    "_volunteer_v_version_positions",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        title: varchar("title"),
        titleFr: varchar("title_fr"),
        description: jsonb("description"),
        descriptionFr: jsonb("description_fr"),
        requirements: jsonb("requirements"),
        requirementsFr: jsonb("requirements_fr"),
        timeCommitment: varchar("time_commitment"),
        timeCommitmentFr: varchar("time_commitment_fr"),
        datePosted: timestamp("date_posted", { mode: "string", withTimezone: true, precision: 3 }),
        formLink: varchar("form_link"),
        isOpen: boolean("is_open").default(true),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_volunteer_v_version_positions_order_idx").on(columns._order),
        _parentIDIdx: index("_volunteer_v_version_positions_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_volunteer_v.id],
            name: "_volunteer_v_version_positions_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _volunteer_v = pgTable(
    "_volunteer_v",
    {
        id: serial("id").primaryKey(),
        version_page: integer("version_page_id").references(() => pages.id, {
            onDelete: "set null",
        }),
        version_title: varchar("version_title"),
        version_titleFr: varchar("version_title_fr"),
        version_description: varchar("version_description"),
        version_descriptionFr: varchar("version_description_fr"),
        version__status: enum__volunteer_v_version_status("version__status").default("draft"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        latest: boolean("latest"),
    },
    (columns) => ({
        _volunteer_v_version_version_page_idx: index("_volunteer_v_version_version_page_idx").on(columns.version_page),
        _volunteer_v_version_version__status_idx: index("_volunteer_v_version_version__status_idx").on(columns.version__status),
        _volunteer_v_created_at_idx: index("_volunteer_v_created_at_idx").on(columns.createdAt),
        _volunteer_v_updated_at_idx: index("_volunteer_v_updated_at_idx").on(columns.updatedAt),
        _volunteer_v_latest_idx: index("_volunteer_v_latest_idx").on(columns.latest),
    }),
);

export const announcement_bar = pgTable(
    "announcement_bar",
    {
        id: serial("id").primaryKey(),
        isEnabled: boolean("is_enabled").default(false),
        message: varchar("message"),
        messageFr: varchar("message_fr"),
        link_text: varchar("link_text"),
        link_textFr: varchar("link_text_fr"),
        link_href: varchar("link_href"),
        _status: enum_announcement_bar_status("_status").default("draft"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        announcement_bar__status_idx: index("announcement_bar__status_idx").on(columns._status),
    }),
);

export const _announcement_bar_v = pgTable(
    "_announcement_bar_v",
    {
        id: serial("id").primaryKey(),
        version_isEnabled: boolean("version_is_enabled").default(false),
        version_message: varchar("version_message"),
        version_messageFr: varchar("version_message_fr"),
        version_link_text: varchar("version_link_text"),
        version_link_textFr: varchar("version_link_text_fr"),
        version_link_href: varchar("version_link_href"),
        version__status: enum__announcement_bar_v_version_status("version__status").default("draft"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        latest: boolean("latest"),
    },
    (columns) => ({
        _announcement_bar_v_version_version__status_idx: index("_announcement_bar_v_version_version__status_idx").on(columns.version__status),
        _announcement_bar_v_created_at_idx: index("_announcement_bar_v_created_at_idx").on(columns.createdAt),
        _announcement_bar_v_updated_at_idx: index("_announcement_bar_v_updated_at_idx").on(columns.updatedAt),
        _announcement_bar_v_latest_idx: index("_announcement_bar_v_latest_idx").on(columns.latest),
    }),
);

export const about_teams_members = pgTable(
    "about_teams_members",
    {
        _order: integer("_order").notNull(),
        _parentID: varchar("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        name: varchar("name"),
        role: varchar("role"),
        pronouns: varchar("pronouns"),
        image: integer("image_id").references(() => media.id, {
            onDelete: "set null",
        }),
    },
    (columns) => ({
        _orderIdx: index("about_teams_members_order_idx").on(columns._order),
        _parentIDIdx: index("about_teams_members_parent_id_idx").on(columns._parentID),
        about_teams_members_image_idx: index("about_teams_members_image_idx").on(columns.image),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [about_teams.id],
            name: "about_teams_members_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const about_teams = pgTable(
    "about_teams",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: varchar("id").primaryKey(),
        teamName: varchar("team_name"),
    },
    (columns) => ({
        _orderIdx: index("about_teams_order_idx").on(columns._order),
        _parentIDIdx: index("about_teams_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [about.id],
            name: "about_teams_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const about = pgTable(
    "about",
    {
        id: serial("id").primaryKey(),
        groupPicture: integer("group_picture_id").references(() => media.id, {
            onDelete: "set null",
        }),
        _status: enum_about_status("_status").default("draft"),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }),
    },
    (columns) => ({
        about_group_picture_idx: index("about_group_picture_idx").on(columns.groupPicture),
        about__status_idx: index("about__status_idx").on(columns._status),
    }),
);

export const _about_v_version_teams_members = pgTable(
    "_about_v_version_teams_members",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        name: varchar("name"),
        role: varchar("role"),
        pronouns: varchar("pronouns"),
        image: integer("image_id").references(() => media.id, {
            onDelete: "set null",
        }),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_about_v_version_teams_members_order_idx").on(columns._order),
        _parentIDIdx: index("_about_v_version_teams_members_parent_id_idx").on(columns._parentID),
        _about_v_version_teams_members_image_idx: index("_about_v_version_teams_members_image_idx").on(columns.image),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_about_v_version_teams.id],
            name: "_about_v_version_teams_members_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _about_v_version_teams = pgTable(
    "_about_v_version_teams",
    {
        _order: integer("_order").notNull(),
        _parentID: integer("_parent_id").notNull(),
        id: serial("id").primaryKey(),
        teamName: varchar("team_name"),
        _uuid: varchar("_uuid"),
    },
    (columns) => ({
        _orderIdx: index("_about_v_version_teams_order_idx").on(columns._order),
        _parentIDIdx: index("_about_v_version_teams_parent_id_idx").on(columns._parentID),
        _parentIDFk: foreignKey({
            columns: [columns["_parentID"]],
            foreignColumns: [_about_v.id],
            name: "_about_v_version_teams_parent_id_fk",
        }).onDelete("cascade"),
    }),
);

export const _about_v = pgTable(
    "_about_v",
    {
        id: serial("id").primaryKey(),
        version_groupPicture: integer("version_group_picture_id").references(() => media.id, {
            onDelete: "set null",
        }),
        version__status: enum__about_v_version_status("version__status").default("draft"),
        version_updatedAt: timestamp("version_updated_at", { mode: "string", withTimezone: true, precision: 3 }),
        version_createdAt: timestamp("version_created_at", { mode: "string", withTimezone: true, precision: 3 }),
        createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 }).defaultNow().notNull(),
        latest: boolean("latest"),
    },
    (columns) => ({
        _about_v_version_version_group_picture_idx: index("_about_v_version_version_group_picture_idx").on(columns.version_groupPicture),
        _about_v_version_version__status_idx: index("_about_v_version_version__status_idx").on(columns.version__status),
        _about_v_created_at_idx: index("_about_v_created_at_idx").on(columns.createdAt),
        _about_v_updated_at_idx: index("_about_v_updated_at_idx").on(columns.updatedAt),
        _about_v_latest_idx: index("_about_v_latest_idx").on(columns.latest),
    }),
);

export const relations_users = relations(users, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_pages = relations(pages, () => ({}));
export const relations_legal = relations(legal, ({ one }) => ({
    page: one(pages, {
        fields: [legal.page],
        references: [pages.id],
        relationName: "page",
    }),
}));
export const relations__legal_v = relations(_legal_v, ({ one }) => ({
    parent: one(legal, {
        fields: [_legal_v.parent],
        references: [legal.id],
        relationName: "parent",
    }),
    version_page: one(pages, {
        fields: [_legal_v.version_page],
        references: [pages.id],
        relationName: "version_page",
    }),
}));
export const relations_events_date_ranges = relations(events_date_ranges, ({ one }) => ({
    _parentID: one(events, {
        fields: [events_date_ranges._parentID],
        references: [events.id],
        relationName: "dateRanges",
    }),
}));
export const relations_events = relations(events, ({ one, many }) => ({
    dateRanges: many(events_date_ranges, {
        relationName: "dateRanges",
    }),
    graphic: one(media, {
        fields: [events.graphic],
        references: [media.id],
        relationName: "graphic",
    }),
}));
export const relations_clubs_other_socials = relations(clubs_other_socials, ({ one }) => ({
    _parentID: one(clubs, {
        fields: [clubs_other_socials._parentID],
        references: [clubs.id],
        relationName: "otherSocials",
    }),
}));
export const relations_clubs_rels = relations(clubs_rels, ({ one }) => ({
    parent: one(clubs, {
        fields: [clubs_rels.parent],
        references: [clubs.id],
        relationName: "_rels",
    }),
    "club-tagsID": one(club_tags, {
        fields: [clubs_rels["club-tagsID"]],
        references: [club_tags.id],
        relationName: "club-tags",
    }),
}));
export const relations_clubs = relations(clubs, ({ one, many }) => ({
    otherSocials: many(clubs_other_socials, {
        relationName: "otherSocials",
    }),
    graphic: one(media, {
        fields: [clubs.graphic],
        references: [media.id],
        relationName: "graphic",
    }),
    _rels: many(clubs_rels, {
        relationName: "_rels",
    }),
}));
export const relations_resources_insurance_providers_insurance_provider = relations(resources_insurance_providers_insurance_provider, ({ one }) => ({
    _parentID: one(resources_insurance_providers, {
        fields: [resources_insurance_providers_insurance_provider._parentID],
        references: [resources_insurance_providers.id],
        relationName: "insuranceProvider",
    }),
}));
export const relations_resources_insurance_providers = relations(resources_insurance_providers, ({ one, many }) => ({
    _parentID: one(resources, {
        fields: [resources_insurance_providers._parentID],
        references: [resources.id],
        relationName: "insuranceProviders",
    }),
    insuranceProvider: many(resources_insurance_providers_insurance_provider, {
        relationName: "insuranceProvider",
    }),
}));
export const relations_resources_rels = relations(resources_rels, ({ one }) => ({
    parent: one(resources, {
        fields: [resources_rels.parent],
        references: [resources.id],
        relationName: "_rels",
    }),
    "resource-tagsID": one(resource_tags, {
        fields: [resources_rels["resource-tagsID"]],
        references: [resource_tags.id],
        relationName: "resource-tags",
    }),
}));
export const relations_resources = relations(resources, ({ one, many }) => ({
    insuranceProviders: many(resources_insurance_providers, {
        relationName: "insuranceProviders",
    }),
    graphic: one(media, {
        fields: [resources.graphic],
        references: [media.id],
        relationName: "graphic",
    }),
    _rels: many(resources_rels, {
        relationName: "_rels",
    }),
}));
export const relations_club_tag_categories = relations(club_tag_categories, () => ({}));
export const relations_resource_tag_categories = relations(resource_tag_categories, () => ({}));
export const relations_club_tags = relations(club_tags, ({ one }) => ({
    category: one(club_tag_categories, {
        fields: [club_tags.category],
        references: [club_tag_categories.id],
        relationName: "category",
    }),
}));
export const relations_resource_tags = relations(resource_tags, ({ one }) => ({
    category: one(resource_tag_categories, {
        fields: [resource_tags.category],
        references: [resource_tag_categories.id],
        relationName: "category",
    }),
}));
export const relations_audit_log = relations(audit_log, ({ one }) => ({
    user: one(users, {
        fields: [audit_log.user],
        references: [users.id],
        relationName: "user",
    }),
}));
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
    parent: one(payload_locked_documents, {
        fields: [payload_locked_documents_rels.parent],
        references: [payload_locked_documents.id],
        relationName: "_rels",
    }),
    usersID: one(users, {
        fields: [payload_locked_documents_rels.usersID],
        references: [users.id],
        relationName: "users",
    }),
    mediaID: one(media, {
        fields: [payload_locked_documents_rels.mediaID],
        references: [media.id],
        relationName: "media",
    }),
    pagesID: one(pages, {
        fields: [payload_locked_documents_rels.pagesID],
        references: [pages.id],
        relationName: "pages",
    }),
    legalID: one(legal, {
        fields: [payload_locked_documents_rels.legalID],
        references: [legal.id],
        relationName: "legal",
    }),
    eventsID: one(events, {
        fields: [payload_locked_documents_rels.eventsID],
        references: [events.id],
        relationName: "events",
    }),
    clubsID: one(clubs, {
        fields: [payload_locked_documents_rels.clubsID],
        references: [clubs.id],
        relationName: "clubs",
    }),
    resourcesID: one(resources, {
        fields: [payload_locked_documents_rels.resourcesID],
        references: [resources.id],
        relationName: "resources",
    }),
    "club-tag-categoriesID": one(club_tag_categories, {
        fields: [payload_locked_documents_rels["club-tag-categoriesID"]],
        references: [club_tag_categories.id],
        relationName: "club-tag-categories",
    }),
    "resource-tag-categoriesID": one(resource_tag_categories, {
        fields: [payload_locked_documents_rels["resource-tag-categoriesID"]],
        references: [resource_tag_categories.id],
        relationName: "resource-tag-categories",
    }),
    "club-tagsID": one(club_tags, {
        fields: [payload_locked_documents_rels["club-tagsID"]],
        references: [club_tags.id],
        relationName: "club-tags",
    }),
    "resource-tagsID": one(resource_tags, {
        fields: [payload_locked_documents_rels["resource-tagsID"]],
        references: [resource_tags.id],
        relationName: "resource-tags",
    }),
    "audit-logID": one(audit_log, {
        fields: [payload_locked_documents_rels["audit-logID"]],
        references: [audit_log.id],
        relationName: "audit-log",
    }),
}));
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
        relationName: "_rels",
    }),
}));
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
    parent: one(payload_preferences, {
        fields: [payload_preferences_rels.parent],
        references: [payload_preferences.id],
        relationName: "_rels",
    }),
    usersID: one(users, {
        fields: [payload_preferences_rels.usersID],
        references: [users.id],
        relationName: "users",
    }),
}));
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
    _rels: many(payload_preferences_rels, {
        relationName: "_rels",
    }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));
export const relations_holistic_wellness_wellness_wheel_dimensions = relations(holistic_wellness_wellness_wheel_dimensions, ({ one }) => ({
    _parentID: one(holistic_wellness, {
        fields: [holistic_wellness_wellness_wheel_dimensions._parentID],
        references: [holistic_wellness.id],
        relationName: "wellnessWheelDimensions",
    }),
}));
export const relations_holistic_wellness_sections = relations(holistic_wellness_sections, ({ one }) => ({
    _parentID: one(holistic_wellness, {
        fields: [holistic_wellness_sections._parentID],
        references: [holistic_wellness.id],
        relationName: "sections",
    }),
}));
export const relations_holistic_wellness = relations(holistic_wellness, ({ one, many }) => ({
    page: one(pages, {
        fields: [holistic_wellness.page],
        references: [pages.id],
        relationName: "page",
    }),
    wellnessWheelDimensions: many(holistic_wellness_wellness_wheel_dimensions, {
        relationName: "wellnessWheelDimensions",
    }),
    sections: many(holistic_wellness_sections, {
        relationName: "sections",
    }),
}));
export const relations__holistic_wellness_v_version_wellness_wheel_dimensions = relations(_holistic_wellness_v_version_wellness_wheel_dimensions, ({ one }) => ({
    _parentID: one(_holistic_wellness_v, {
        fields: [_holistic_wellness_v_version_wellness_wheel_dimensions._parentID],
        references: [_holistic_wellness_v.id],
        relationName: "version_wellnessWheelDimensions",
    }),
}));
export const relations__holistic_wellness_v_version_sections = relations(_holistic_wellness_v_version_sections, ({ one }) => ({
    _parentID: one(_holistic_wellness_v, {
        fields: [_holistic_wellness_v_version_sections._parentID],
        references: [_holistic_wellness_v.id],
        relationName: "version_sections",
    }),
}));
export const relations__holistic_wellness_v = relations(_holistic_wellness_v, ({ one, many }) => ({
    version_page: one(pages, {
        fields: [_holistic_wellness_v.version_page],
        references: [pages.id],
        relationName: "version_page",
    }),
    version_wellnessWheelDimensions: many(_holistic_wellness_v_version_wellness_wheel_dimensions, {
        relationName: "version_wellnessWheelDimensions",
    }),
    version_sections: many(_holistic_wellness_v_version_sections, {
        relationName: "version_sections",
    }),
}));
export const relations_sponsor_sponsors = relations(sponsor_sponsors, ({ one }) => ({
    _parentID: one(sponsor, {
        fields: [sponsor_sponsors._parentID],
        references: [sponsor.id],
        relationName: "sponsors",
    }),
    logo: one(media, {
        fields: [sponsor_sponsors.logo],
        references: [media.id],
        relationName: "logo",
    }),
}));
export const relations_sponsor = relations(sponsor, ({ one, many }) => ({
    page: one(pages, {
        fields: [sponsor.page],
        references: [pages.id],
        relationName: "page",
    }),
    sponsors: many(sponsor_sponsors, {
        relationName: "sponsors",
    }),
}));
export const relations__sponsor_v_version_sponsors = relations(_sponsor_v_version_sponsors, ({ one }) => ({
    _parentID: one(_sponsor_v, {
        fields: [_sponsor_v_version_sponsors._parentID],
        references: [_sponsor_v.id],
        relationName: "version_sponsors",
    }),
    logo: one(media, {
        fields: [_sponsor_v_version_sponsors.logo],
        references: [media.id],
        relationName: "logo",
    }),
}));
export const relations__sponsor_v = relations(_sponsor_v, ({ one, many }) => ({
    version_page: one(pages, {
        fields: [_sponsor_v.version_page],
        references: [pages.id],
        relationName: "version_page",
    }),
    version_sponsors: many(_sponsor_v_version_sponsors, {
        relationName: "version_sponsors",
    }),
}));
export const relations_volunteer_positions = relations(volunteer_positions, ({ one }) => ({
    _parentID: one(volunteer, {
        fields: [volunteer_positions._parentID],
        references: [volunteer.id],
        relationName: "positions",
    }),
}));
export const relations_volunteer = relations(volunteer, ({ one, many }) => ({
    page: one(pages, {
        fields: [volunteer.page],
        references: [pages.id],
        relationName: "page",
    }),
    positions: many(volunteer_positions, {
        relationName: "positions",
    }),
}));
export const relations__volunteer_v_version_positions = relations(_volunteer_v_version_positions, ({ one }) => ({
    _parentID: one(_volunteer_v, {
        fields: [_volunteer_v_version_positions._parentID],
        references: [_volunteer_v.id],
        relationName: "version_positions",
    }),
}));
export const relations__volunteer_v = relations(_volunteer_v, ({ one, many }) => ({
    version_page: one(pages, {
        fields: [_volunteer_v.version_page],
        references: [pages.id],
        relationName: "version_page",
    }),
    version_positions: many(_volunteer_v_version_positions, {
        relationName: "version_positions",
    }),
}));
export const relations_announcement_bar = relations(announcement_bar, () => ({}));
export const relations__announcement_bar_v = relations(_announcement_bar_v, () => ({}));
export const relations_about_teams_members = relations(about_teams_members, ({ one }) => ({
    _parentID: one(about_teams, {
        fields: [about_teams_members._parentID],
        references: [about_teams.id],
        relationName: "members",
    }),
    image: one(media, {
        fields: [about_teams_members.image],
        references: [media.id],
        relationName: "image",
    }),
}));
export const relations_about_teams = relations(about_teams, ({ one, many }) => ({
    _parentID: one(about, {
        fields: [about_teams._parentID],
        references: [about.id],
        relationName: "teams",
    }),
    members: many(about_teams_members, {
        relationName: "members",
    }),
}));
export const relations_about = relations(about, ({ one, many }) => ({
    groupPicture: one(media, {
        fields: [about.groupPicture],
        references: [media.id],
        relationName: "groupPicture",
    }),
    teams: many(about_teams, {
        relationName: "teams",
    }),
}));
export const relations__about_v_version_teams_members = relations(_about_v_version_teams_members, ({ one }) => ({
    _parentID: one(_about_v_version_teams, {
        fields: [_about_v_version_teams_members._parentID],
        references: [_about_v_version_teams.id],
        relationName: "members",
    }),
    image: one(media, {
        fields: [_about_v_version_teams_members.image],
        references: [media.id],
        relationName: "image",
    }),
}));
export const relations__about_v_version_teams = relations(_about_v_version_teams, ({ one, many }) => ({
    _parentID: one(_about_v, {
        fields: [_about_v_version_teams._parentID],
        references: [_about_v.id],
        relationName: "version_teams",
    }),
    members: many(_about_v_version_teams_members, {
        relationName: "members",
    }),
}));
export const relations__about_v = relations(_about_v, ({ one, many }) => ({
    version_groupPicture: one(media, {
        fields: [_about_v.version_groupPicture],
        references: [media.id],
        relationName: "version_groupPicture",
    }),
    version_teams: many(_about_v_version_teams, {
        relationName: "version_teams",
    }),
}));

type DatabaseSchema = {
    enum_users_role: typeof enum_users_role;
    enum_legal_status: typeof enum_legal_status;
    enum__legal_v_version_status: typeof enum__legal_v_version_status;
    enum_audit_log_operation: typeof enum_audit_log_operation;
    enum_sponsor_status: typeof enum_sponsor_status;
    enum__sponsor_v_version_status: typeof enum__sponsor_v_version_status;
    enum_volunteer_status: typeof enum_volunteer_status;
    enum__volunteer_v_version_status: typeof enum__volunteer_v_version_status;
    enum_announcement_bar_status: typeof enum_announcement_bar_status;
    enum__announcement_bar_v_version_status: typeof enum__announcement_bar_v_version_status;
    enum_about_status: typeof enum_about_status;
    enum__about_v_version_status: typeof enum__about_v_version_status;
    users: typeof users;
    media: typeof media;
    pages: typeof pages;
    legal: typeof legal;
    _legal_v: typeof _legal_v;
    events_date_ranges: typeof events_date_ranges;
    events: typeof events;
    clubs_other_socials: typeof clubs_other_socials;
    clubs: typeof clubs;
    clubs_rels: typeof clubs_rels;
    resources_insurance_providers_insurance_provider: typeof resources_insurance_providers_insurance_provider;
    resources_insurance_providers: typeof resources_insurance_providers;
    resources: typeof resources;
    resources_rels: typeof resources_rels;
    club_tag_categories: typeof club_tag_categories;
    resource_tag_categories: typeof resource_tag_categories;
    club_tags: typeof club_tags;
    resource_tags: typeof resource_tags;
    audit_log: typeof audit_log;
    payload_locked_documents: typeof payload_locked_documents;
    payload_locked_documents_rels: typeof payload_locked_documents_rels;
    payload_preferences: typeof payload_preferences;
    payload_preferences_rels: typeof payload_preferences_rels;
    payload_migrations: typeof payload_migrations;
    holistic_wellness_wellness_wheel_dimensions: typeof holistic_wellness_wellness_wheel_dimensions;
    holistic_wellness_sections: typeof holistic_wellness_sections;
    holistic_wellness: typeof holistic_wellness;
    _holistic_wellness_v_version_wellness_wheel_dimensions: typeof _holistic_wellness_v_version_wellness_wheel_dimensions;
    _holistic_wellness_v_version_sections: typeof _holistic_wellness_v_version_sections;
    _holistic_wellness_v: typeof _holistic_wellness_v;
    sponsor_sponsors: typeof sponsor_sponsors;
    sponsor: typeof sponsor;
    _sponsor_v_version_sponsors: typeof _sponsor_v_version_sponsors;
    _sponsor_v: typeof _sponsor_v;
    volunteer_positions: typeof volunteer_positions;
    volunteer: typeof volunteer;
    _volunteer_v_version_positions: typeof _volunteer_v_version_positions;
    _volunteer_v: typeof _volunteer_v;
    announcement_bar: typeof announcement_bar;
    _announcement_bar_v: typeof _announcement_bar_v;
    about_teams_members: typeof about_teams_members;
    about_teams: typeof about_teams;
    about: typeof about;
    _about_v_version_teams_members: typeof _about_v_version_teams_members;
    _about_v_version_teams: typeof _about_v_version_teams;
    _about_v: typeof _about_v;
    relations_users: typeof relations_users;
    relations_media: typeof relations_media;
    relations_pages: typeof relations_pages;
    relations_legal: typeof relations_legal;
    relations__legal_v: typeof relations__legal_v;
    relations_events_date_ranges: typeof relations_events_date_ranges;
    relations_events: typeof relations_events;
    relations_clubs_other_socials: typeof relations_clubs_other_socials;
    relations_clubs_rels: typeof relations_clubs_rels;
    relations_clubs: typeof relations_clubs;
    relations_resources_insurance_providers_insurance_provider: typeof relations_resources_insurance_providers_insurance_provider;
    relations_resources_insurance_providers: typeof relations_resources_insurance_providers;
    relations_resources_rels: typeof relations_resources_rels;
    relations_resources: typeof relations_resources;
    relations_club_tag_categories: typeof relations_club_tag_categories;
    relations_resource_tag_categories: typeof relations_resource_tag_categories;
    relations_club_tags: typeof relations_club_tags;
    relations_resource_tags: typeof relations_resource_tags;
    relations_audit_log: typeof relations_audit_log;
    relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
    relations_payload_locked_documents: typeof relations_payload_locked_documents;
    relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
    relations_payload_preferences: typeof relations_payload_preferences;
    relations_payload_migrations: typeof relations_payload_migrations;
    relations_holistic_wellness_wellness_wheel_dimensions: typeof relations_holistic_wellness_wellness_wheel_dimensions;
    relations_holistic_wellness_sections: typeof relations_holistic_wellness_sections;
    relations_holistic_wellness: typeof relations_holistic_wellness;
    relations__holistic_wellness_v_version_wellness_wheel_dimensions: typeof relations__holistic_wellness_v_version_wellness_wheel_dimensions;
    relations__holistic_wellness_v_version_sections: typeof relations__holistic_wellness_v_version_sections;
    relations__holistic_wellness_v: typeof relations__holistic_wellness_v;
    relations_sponsor_sponsors: typeof relations_sponsor_sponsors;
    relations_sponsor: typeof relations_sponsor;
    relations__sponsor_v_version_sponsors: typeof relations__sponsor_v_version_sponsors;
    relations__sponsor_v: typeof relations__sponsor_v;
    relations_volunteer_positions: typeof relations_volunteer_positions;
    relations_volunteer: typeof relations_volunteer;
    relations__volunteer_v_version_positions: typeof relations__volunteer_v_version_positions;
    relations__volunteer_v: typeof relations__volunteer_v;
    relations_announcement_bar: typeof relations_announcement_bar;
    relations__announcement_bar_v: typeof relations__announcement_bar_v;
    relations_about_teams_members: typeof relations_about_teams_members;
    relations_about_teams: typeof relations_about_teams;
    relations_about: typeof relations_about;
    relations__about_v_version_teams_members: typeof relations__about_v_version_teams_members;
    relations__about_v_version_teams: typeof relations__about_v_version_teams;
    relations__about_v: typeof relations__about_v;
};

declare module "@payloadcms/db-postgres" {
    export interface GeneratedDatabaseSchema {
        schema: DatabaseSchema;
    }
}
