name: Backup Payload Database to S3

on:
    schedule:
        - cron: "42 8 * * *" # run at 08:42 UTC (03:42 EST) every day
    workflow_dispatch: # allows manual triggering from GitHub UI

permissions:
    id-token: write
    contents: read

jobs:
    backup_and_upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install PostgreSQL client
              run: |
                  sudo apt install -y postgresql-common
                  yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
                  sudo apt-get install -y postgresql-client-16

            - name: Set timestamp
              run: echo "TIMESTAMP=$(date -u +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

            - name: Dump database
              run: |
                  /usr/lib/postgresql/16/bin/pg_dump ${{ secrets.DB_CONNECTION }} | gzip > "${TIMESTAMP}.sql.gz"

            - name: Configure AWS credentials from Action OIDC
              uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
              with:
                  aws-region: ${{ secrets.AWS_REGION }}
                  role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/s3-mindvista-postgres-backup-github-actions
                  role-session-name: GitHubActionSession

            - name: Upload backup to S3
              run: |
                  YEAR_MONTH=$(date -u +"%Y/%m")
                  aws s3 cp "${TIMESTAMP}.sql.gz" s3://mindvista-payload-backups/database/${YEAR_MONTH}/
