name: Cleanup PR Environment

on:
    pull_request:
        types: [closed]

permissions:
    pull-requests: write

jobs:
    cleanup_preview:
        name: Cleanup Staging Environment
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.pull_request.number }}
        steps:
            # download the artifact containing deployment URL
            - uses: actions/download-artifact@v4
              with:
                  name: pr-${{ env.PR_NUMBER }}-deploy-url
                  path: .

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Delete Vercel Preview Deployment
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |
                  if [ -f "pr-deploy-mapping.json" ]; then
                      DEPLOY_URL=$(jq -r '.url' pr-deploy-mapping.json)
                      if [ ! -z "$DEPLOY_URL" ]; then
                          echo "Found deployment URL: $DEPLOY_URL"
                          vercel remove "$DEPLOY_URL" -y --token=$VERCEL_TOKEN
                          echo "Deleted Vercel preview deployment for PR #${PR_NUMBER}."
                      else
                          echo "No deployment URL found in mapping file. Skipping deletion."
                      fi
                  else
                      echo "WARN: No deployment mapping file found."
                  fi

            - name: Delete redirect rule
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo "Looking up redirect rule for PR #${PR_NUMBER}..."

                  # list existing redirect rules
                  EXISTING_RULES=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/rules/redirect" \
                    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
                    -H "Content-Type: application/json")

                  # check if rule exists by looking for PR number in description
                  RULE_ID=$(echo "$EXISTING_RULES" | jq -r ".result[] | select(.description | contains(\"PR #${PR_NUMBER}\")) | .id")

                  if [ -n "$RULE_ID" ]; then
                      echo "Found redirect rule. Deleting..."

                      # delete the rule
                      DELETE_RESULT=$(curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/rules/redirect/${RULE_ID}" \
                        -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
                        -H "Content-Type: application/json")

                      SUCCESS=$(echo "$DELETE_RESULT" | jq -r '.success')

                      if [ "$SUCCESS" = "true" ]; then
                          echo "Successfully deleted redirect rule for PR #${PR_NUMBER}."
                          gh pr comment ${PR_NUMBER} --body "🧹 PR closed or merged. Staging URL has been deleted."
                      else
                          echo "Failed to delete redirect rule:"
                          echo "$DELETE_RESULT" | jq '.'
                          exit 1
                      fi
                  else
                      echo "No redirect rule found for PR #${PR_NUMBER}. Nothing to delete."
                  fi

            - name: Delete Artifact
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ARTIFACT_NAME="pr-${PR_NUMBER}-deploy-url"

                  echo "Fetching artifacts for the repository..."
                  ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts)

                  ARTIFACT_ID=$(echo "$ARTIFACTS" | jq ".artifacts[] | select(.name == \"$ARTIFACT_NAME\") | .id")

                  if [ -n "$ARTIFACT_ID" ]; then
                      echo "Found artifact ID: $ARTIFACT_ID. Deleting..."
                      gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID
                      echo "Artifact deleted successfully."
                  else
                      echo "No matching artifact found to delete."
                  fi
