name: Deploy to Production

on:
    push:
        branches: [master]
    workflow_dispatch: # manual triggering for external fork PRs

permissions:
    contents: read
    deployments: write

concurrency:
    group: deploy-production
    cancel-in-progress: true

jobs:
    deploy_prod:
        name: Deploy for Production
        runs-on: ubuntu-latest
        environment:
            name: Production
            url: ${{ steps.deploy-prod.outputs.url }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              id: deploy-prod
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
              run: |
                  DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
                  echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
