name: Deploy to Preview

on:
    # called by pr-checks.yml only if on base repository (skips for forks)
    workflow_call:
        outputs:
            url:
                description: "The deployment URL from Vercel"
                value: ${{ jobs.deploy_preview.outputs.url }}
        secrets:
            VERCEL_TOKEN:
                required: true
            VERCEL_ORG_ID:
                required: true
            VERCEL_PROJECT_ID:
                required: true
            ENCODED_NEON_DATABASE_URL:
                required: true

    workflow_dispatch: # manual triggering for external fork PRs
        inputs:
            pr_number:
                description: "Pull Request Number"
                required: true
                type: number

permissions:
    contents: read
    deployments: write

# ensures only one deployment per ref/branch runs at a time
concurrency:
    group: deploy-preview-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy_preview:
        timeout-minutes: 10
        name: Deploy to Preview
        runs-on: ubuntu-latest
        outputs:
            url: ${{ steps.deploy-preview.outputs.url }}
        environment:
            name: Preview
            url: ${{ steps.deploy-preview.outputs.url }}

        steps:
            - uses: actions/checkout@v4
              with:
                  # for workflow_dispatch (fork PRs), use PR number
                  # for workflow_call (base repo), use branch ref
                  ref: ${{ inputs.pr_number != null && format('refs/pull/{0}/merge', inputs.pr_number) || github.ref }}
                  repository: ${{ github.repository }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Link Vercel Project
              run: vercel link --yes --scope agvq --project mindvista --token=${{ secrets.VERCEL_TOKEN }}

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Decode DB URL and Set for Build
              id: decode_db_url
              env:
                  ENCODED_URL_FROM_SECRET: ${{ secrets.ENCODED_NEON_DATABASE_URL }}
              if: env.ENCODED_URL_FROM_SECRET != ''
              run: |
                  decoded_url=$(echo -n "${{ env.ENCODED_URL_FROM_SECRET }}" | base64 --decode)
                  echo "POSTGRES_URL_DECODED=${decoded_url}" >> $GITHUB_ENV
                  echo "::add-mask::${decoded_url}" # Mask the decoded URL in logs
              shell: bash

            - name: Build Project Artifacts
              env:
                  POSTGRES_URL: ${{ env.POSTGRES_URL_DECODED }}
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              id: deploy-preview
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

              run: |
                  DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
                  echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
