name: Deploy

on:
    push:
        branches: [master]
    pull_request:
        branches: ["**"]
    workflow_dispatch: # manual triggering for external fork PRs

permissions:
    contents: read
    deployments: write

# ensures only one deployment per ref/branch runs at a time
concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy to ${{ github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
        # skip running on PRs from forks, these should be deployed manually by a trusted collaborator via workflow_dispatch
        # see https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/ for more info
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
            url: ${{ steps.deploy.outputs.url }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build ${{ github.ref == 'refs/heads/master' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              id: deploy
              run: |
                  DEPLOYMENT_URL=$(vercel deploy --prebuilt ${{ github.ref == 'refs/heads/master' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }})
                  echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
