name: Enforce Prettier

on:
    workflow_call: # reusable (able to be called by other workflows)

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"

            - name: Cache npm cache
              id: cache-npm
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-

            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  npx commitlint --version

            - name: Install dependencies
              run: npm ci

            - name: Check Prettier formatting
              id: prettier-check
              run: |
                  if npx prettier --check .; then
                    echo "Files are properly formatted."
                    echo "needs_formatting=false" >> $GITHUB_ENV
                  else
                    echo "Prettier formatting required."
                    echo "needs_formatting=true" >> $GITHUB_ENV
                  fi

            - name: Run Prettier
              if: env.needs_formatting == 'true'
              run: npx prettier --write .

            - name: Commit and push changes
              if: env.needs_formatting == 'true'
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

                  # get the current branch name or PR head ref
                  BRANCH_NAME=${{ github.head_ref || github.ref_name }}

                  # switch to the target branch
                  git checkout "$BRANCH_NAME"

                  git commit -am "refactor: format files with prettier"
                  git push origin "$BRANCH_NAME"
                  echo "Formatted and pushed to $BRANCH_NAME"
