name: Playwright Tests
on:
    pull_request:
        branches: [master]
jobs:
    test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF.
                  # See https://github.com/actions/checkout for more details.
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run changed Playwright tests # fail fast: https://playwright.dev/docs/ci#fail-fast
              run: npx playwright test --only-changed=$GITHUB_BASE_REF
              if: github.event_name == 'pull_request'
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
