name: Vercel Deploy

on:
    workflow_call:
        inputs:
            PRODUCTION:
                required: true
                type: boolean
                description: "Whether to create a production deployment"
        outputs:
            url:
                description: "The deployment URL"
                value: ${{ jobs.deploy.outputs.deployment_url }}
        secrets:
            VERCEL_TOKEN:
                required: true
            VERCEL_ORG_ID:
                required: true
            VERCEL_PROJECT_ID:
                required: true

permissions:
    contents: read
    deployments: write

jobs:
    deploy:
        name: Deploy to ${{ inputs.PRODUCTION && 'Production' || 'Preview' }}
        runs-on: ubuntu-latest
        environment:
            name: ${{ inputs.PRODUCTION && 'Production' || 'Preview' }}
            url: ${{ steps.deploy.outputs.url }}
        outputs:
            deployment_url: ${{ steps.deploy.outputs.url }}
        steps:
            - uses: actions/checkout@v4

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=${{ inputs.PRODUCTION && 'Production' || 'Preview' }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build ${{ inputs.PRODUCTION && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              id: deploy
              run: |
                  DEPLOYMENT_URL=$(vercel deploy --prebuilt ${{ inputs.PRODUCTION && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }})
                  echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
