name: Vercel Production Deployment

on:
    workflow_dispatch: # manual triggering from Github's UI
    workflow_call: # reusable (able to be called by other workflows)
        secrets:
            VERCEL_TOKEN:
                required: true
            VERCEL_ORG_ID:
                required: true
            VERCEL_PROJECT_ID:
                required: true

permissions:
    contents: read

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
